# Версия docker-compose
version: '3.7'
# Список наших сервисов (контейнеров)
services:
  master1:
    image: mariadb:10.3
    ports:
      - "3307:3306"
    restart: always
    container_name: master1
    volumes:
      - ./masters/master1/data:/var/lib/mysql
      - ./masters/master1/conf:/etc/mysql/conf.d
      - ./mysql_dump:/docker-entrypoint-initdb.d
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replication
#    networks:
#      - internal
  master2:
    image: mariadb:10.3
    ports:
      - "3308:3306"
    restart: always
    container_name: master2
    links:
      - master1
    volumes:
      - ./masters/master2/data:/var/lib/mysql
      - ./masters/master2/conf:/etc/mysql/conf.d
      - ./mysql_dump:/docker-entrypoint-initdb.d
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replication
#    networks:
#      - internal
#  mariadb_slave2:
#    image: mariadb:10.3
#    ports:
#      - "3309:3306"
#    restart: always
#    links:
#      - mariadb_master
#    volumes:
#      - ./mysql_slave2:/var/lib/mysql
#      - ./conf_slave2:/etc/mysql/conf.d
#      - ./mysql_dump:/docker-entrypoint-initdb.d
#    # задаем пароль для root пользователя
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: replication
#    networks:
#      - internal
#networks:
#  internal:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.100.0/28