# Версия docker-compose
version: '3.7'
# Список наших сервисов (контейнеров)
services:
  master1:
    image: mariadb:10.3
    ports:
      - "3307:3306"
    restart: always
    container_name: master1
    volumes:
      - ./masters/master1/data:/var/lib/mysql
      - ./masters/master1/conf:/etc/mysql/conf.d
      - ./mysql_dump:/docker-entrypoint-initdb.d
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replication
#    networks:
#      - internal
  master2:
    image: mariadb:10.3
    ports:
      - "3308:3306"
    restart: always
    container_name: master2
    links:
      - master1
    volumes:
      - ./masters/master2/data:/var/lib/mysql
      - ./masters/master2/conf:/etc/mysql/conf.d
      - ./mysql_dump:/docker-entrypoint-initdb.d
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replication